# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Mechanize-Plugin-AutoWrite
version:      0.03_01
version_from: lib/WWW/Mechanize/Plugin/AutoWrite.pm
installdirs:  site
requires:
    File::Basename:                0
    File::Path:                    0
    File::Slurp:                   0
    File::Spec:                    0
    File::Temp:                    0
    MIME::Types:                   0
    Test::Differences:             0
    Test::More:                    0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
